import { Navbar } from './components/navbar/navbar'
import './globals.css'
import styles from './page.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <Navbar />
        </header>

        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html >
  )
}
