"use client"
import './styles/globals.css'
import { SessionProvider } from "next-auth/react"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface IProps {
  children: React.ReactNode
  session: any
}

export default function RootLayout({
  children,
  session

}: IProps) {

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body>{children}</body>
      </html >
    </SessionProvider>

  )
}
